{% set version = "0.0.1" %}
package:
  name: marvin_modeling
  version: {{ version }}

source:
  url: http://localhost:8000/dist/work-{{ version }}.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here.

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - notebook >=4.0.0,<5.0
    - ipython >=4.1.0
    - jupyter_cms
    - pandas
    - seaborn
    - scikit-learn
    - sklearn-pandas
    - sklearn2pmml

  run:
    - python
    - notebook >=4.0.0,<5.0
    - ipython >=4.1.0
    - jupyter_cms
    - pandas
    - seaborn
    - scikit-learn
    - sklearn-pandas
    - sklearn2pmml

test:
  # Python imports
  imports:
    - work
    - work.marvin.binary_classification_evaluation
    - work.marvin.binary_classifier_models
    - work.marvin.dataPrepareforTraining

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  #  - jupyter-nbdiff --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: git@git.creditx.com:marvin/jupyter_nbdiff.git
  license: BSD License
  summary: 'Extension for Jupyter Notebook 4.0.x with experimental diff features'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
